- playerViews:
  - name: NewPlayer
    walkingImageSrc: resources/black_knight/asd.png
    idleImageSrc: resources/black_knight/warriorStanding.png
    runningImageSrc: resources/black_knight/asd.png
    attackImageSrc: resources/black_knight/warriorAttack.png
    idleBlockingImageSrc: resources/black_knight/warriorBlockingAnim.png
    imageWidth: 128
    imageHeight: 128
    numberOfClips: 8
    anchorPixel: [64, 70]
    baseRows: 1
    baseCols: 1
    delay: 0.5
- gameConfiguration:
    serverIP: 127.0.0.1
    serverPort: 32001
    fps: 30
    delay: 10
    movementMargin: 90
    gameMusic: resources/sound/NamiLogin.ogg
    fullscreen: false
    screenAutoConfig: false
    defaultScreenHeight: 700
    defaultScreenWidth: 1200
    defaultBPP: 0
    menuBackImage: resources/lich.jpg
    menuBackMusic: resources/sound/QuinnLogin.ogg
    tileWidth: 70
    tileHeight: 50
- playerLocations:
  - name: NewPlayer
    position: [9, 9, 0]
    speed:
      magnitude: 4
      direction: [1, 2]
    powers:
      - name: Club
        damage: 2
        range: 1
      - name: Fist
        damage: 3
        range: 1
    mainPlayer: true
    viewRange: 500