- playerViews:
  - name: player
    imageSrc: resources/black_knight.png
    imageWidth: 96
    imageHeight: 96
    numberOfClips: 8
    anchorPixel: [48, 50]
    baseWidth: 1
    baseHeight: 1
- entityViews:
  - name: windmill
    imageSrc: resources/windmill.png
    imageWidth: 224
    imageHeight: 240
    numberOfClips: 23
    anchorPixel: [112, 120]
    fps: 5
    delay: 3 
    animationRepeats: 4
  - name: watermill
    imageSrc: resources/watermill tileset.png
    imageWidth: 242
    imageHeight: 235
    numberOfClips: 31
    anchorPixel: [121, 105]
  - name: tree
    imageSrc: resources/trees.png
    imageWidth: 129
    imageHeight: 122
    numberOfClips: 0
    anchorPixel: [65, 61]
  - name: barracks
    imageSrc: resources/barracks.png
    imageWidth: 320
    imageHeight: 290
    numberOfClips: 0
    anchorPixel: [180, 195]
  - name: farmhouse
    imageSrc: resources/farmhouse.png
    imageWidth: 238
    imageHeight: 290
    numberOfClips: 0
    anchorPixel: [119, 145]   
- gameConfiguration:
    fps: 30
    delay: 10
    gameMusic: resources/sound/NamiLogin.ogg
    defaultScreenHeight: 690
    defaultScreenWidth: 1280
    defaultBPP: 0
    menuBackImage: resources/lich.jpg
    menuBackMusic: resources/sound/pirates.ogg
- tiles:
  - identifier: soil
    imageSrc: resources/texturesTiles/dirtTile.png
  - identifier: neutral
    imageSrc: resources/texturesTiles/grass.png
  - identifier: water
    imageSrc: resources/texturesTiles/Water.png
  - identifier: tree
    imageSrc: resources/texturesTiles/stonebrick.png
- mapDimensions: [50, 50]
- playerLocations:
  - name: player
    position: [20, 20, 0]
    speed:
      magnitude: 2
      direction: [1, 2]
    powers:
      - name: Club
        damage: 2
        range: 1
      - name: Fist
        damage: 3
        range: 1
- entityLocations:
  - name: windmill
    position: [10, 20, 0]
  - name: tree
    position: [2, 4, 0]
  - name: tree
    position: [3, 8, 0]
  - name: tree
    position: [15, 10, 0]
  - name: barracks
    position: [12, 5, 0]
  - name: watermill
    position: [5, 5, 0]
  - name: farmhouse
    position: [13, 13, 0]
- tileLocations:
  - position: [0, 7, 0]
    texture: water
  - position: [1, 7, 0]
    texture: water   
  - position: [2, 7, 0]
    texture: water   
  - position: [3, 7, 0]
    texture: water    
  - position: [4, 7, 0]
    texture: water
  - position: [5, 7, 0]
    texture: water
  - position: [6, 7, 0]
    texture: water
  - position: [7, 7, 0]
    texture: water
  - position: [8, 7, 0]
    texture: water
  - position: [9, 7, 0]
    texture: water
  - position: [9, 6, 0]
    texture: water
  - position: [9, 5, 0]
    texture: water
  - position: [9, 4, 0]
    texture: water
  - position: [9, 3, 0]
    texture: water
  - position: [9, 2, 0]
    texture: water
  - position: [9, 1, 0]
    texture: water
  - position: [9, 0, 0]
    texture: water
  - position: [0, 0, 0]
    texture: soil
  - position: [1, 0, 0]
    texture: soil
  - position: [2, 0, 0]
    texture: soil
  - position: [0, 1, 0]
    texture: soil
  - position: [0, 2, 0]
    texture: soil
  - position: [1, 1, 0]
    texture: soil
  - position: [2, 1, 0]
    texture: soil
  - position: [1, 2, 0]
    texture: soil
  - position: [2, 2, 0]
    texture: soil
  - position: [5, 5, 0]
    texture: tree
  - position: [5, 6, 0]
    texture: water
  - position: [6, 6, 0]
    texture: soil
  - position: [20, 20, 0]
    texture: soil
